# Generated by Django 4.2.11 on 2025-08-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progressupdate_evidence_files_evidencefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressupdate',
            name='approval_comments',
            field=models.TextField(blank=True, help_text='Comments from the approver'),
        ),
    ]
