# Generated by Django 4.2.7 on 2025-08-20 09:22

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_code', models.CharField(help_text="e.g., 'FY 2024/25'", max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one financial year can be active at a time')),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Year',
                'verbose_name_plural': 'Financial Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='KPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('strategic_objective', models.TextField(help_text='High-level strategic objective this KPA supports')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for KPAs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpas', to='core.financialyear')),
                ('owner', models.ForeignKey(help_text='Senior Manager responsible for this KPA', on_delete=django.db.models.deletion.PROTECT, related_name='owned_kpas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPA',
                'verbose_name_plural': 'KPAs',
                'ordering': ['order', 'title'],
                'unique_together': {('title', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='OperationalPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output', models.TextField(help_text='What is delivered - goods/services produced')),
                ('activities', models.JSONField(default=list, help_text='List of actions taken to deliver the output')),
                ('targets', models.TextField(help_text='Desired measurable results')),
                ('indicator', models.CharField(help_text='How progress/success is measured', max_length=500)),
                ('inputs', models.JSONField(default=list, help_text='Resources required (human, financial, material)')),
                ('input_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost of inputs required', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('output_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost to deliver the output', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('timeframe', models.CharField(help_text='When the output should be delivered', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget_programme', models.CharField(help_text='Budget programme classification', max_length=200)),
                ('budget_objective', models.CharField(help_text='Budget objective classification', max_length=200)),
                ('budget_responsibility', models.CharField(help_text='Budget responsibility center', max_length=200)),
                ('responsible_officer', models.CharField(help_text='Name of the officer responsible for delivery', max_length=200)),
                ('unit_subdirectorate', models.CharField(blank=True, help_text='Unit or Sub-Directorate responsible', max_length=200)),
                ('office', models.CharField(blank=True, help_text='Office location or designation', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('kpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='core.kpa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operational Plan Item',
                'verbose_name_plural': 'Operational Plan Items',
                'ordering': ['kpa__order', 'id'],
            },
        ),
    ]
