# Generated by Django 4.2.7 on 2025-08-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationalplanitem',
            old_name='targets',
            new_name='target_description',
        ),
    ]
