# Generated by Django 4.2.7 on 2025-08-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orgunit_kpa_org_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='unit_type',
            field=models.CharField(choices=[('CEO_OFFICE', 'CEO Office'), ('CHIEF_DIRECTORATE', 'Chief Directorate'), ('DIRECTORATE', 'Directorate'), ('SUB_DIRECTORATE', 'Sub-Directorate')], max_length=20),
        ),
    ]
