# Generated by Django 4.2.7 on 2025-08-20 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_orgunit_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(help_text='Unique employee identifier', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('id_number', models.CharField(blank=True, help_text='National ID number', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern'), ('CONSULTANT', 'Consultant')], default='PERMANENT', max_length=20)),
                ('salary_level', models.CharField(blank=True, help_text='e.g., Level 8, Senior Manager', max_length=50)),
                ('start_date', models.DateField(help_text='Employment start date')),
                ('end_date', models.DateField(blank=True, help_text='Contract end date (if applicable)', null=True)),
                ('highest_qualification', models.CharField(blank=True, choices=[('MATRIC', 'Matric/Grade 12'), ('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('DEGREE', "Bachelor's Degree"), ('HONOURS', 'Honours Degree'), ('MASTERS', "Master's Degree"), ('DOCTORATE', 'Doctorate'), ('OTHER', 'Other')], max_length=20)),
                ('qualification_details', models.TextField(blank=True, help_text='Detailed qualification information')),
                ('skills', models.TextField(blank=True, help_text='Key skills and competencies')),
                ('physical_address', models.TextField(blank=True)),
                ('postal_address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('performance_rating', models.CharField(blank=True, help_text='Latest performance rating', max_length=50)),
                ('development_needs', models.TextField(blank=True, help_text='Training and development needs')),
                ('is_active', models.BooleanField(default=True, help_text='Currently employed')),
                ('is_manager', models.BooleanField(default=False, help_text='Has management responsibilities')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.orgunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['org_unit', 'last_name', 'first_name'],
            },
        ),
    ]
