# Generated by Django 4.2.7 on 2025-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='persal_number',
            field=models.CharField(blank=True, help_text='Unique PERSAL number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary_level',
            field=models.CharField(blank=True, choices=[('LEVEL_1', 'Level 1 - General Assistant'), ('LEVEL_2', 'Level 2 - General Assistant'), ('LEVEL_3', 'Level 3 - General Assistant'), ('LEVEL_4', 'Level 4 - Administrative Officer'), ('LEVEL_5', 'Level 5 - Administrative Officer'), ('LEVEL_6', 'Level 6 - Senior Administrative Officer'), ('LEVEL_7', 'Level 7 - Senior Administrative Officer'), ('LEVEL_8', 'Level 8 - Assistant Director'), ('LEVEL_9', 'Level 9 - Assistant Director'), ('LEVEL_10', 'Level 10 - Deputy Director'), ('LEVEL_11', 'Level 11 - Deputy Director'), ('LEVEL_12', 'Level 12 - Director'), ('LEVEL_13', 'Level 13 - Chief Director'), ('LEVEL_14', 'Level 14 - Deputy Director-General'), ('LEVEL_15', 'Level 15 - Director-General')], help_text='Public service salary level', max_length=20),
        ),
    ]
