# Generated by Django 4.2.7 on 2025-08-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_persal_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='employee_number',
        ),
        migrations.AlterField(
            model_name='staff',
            name='persal_number',
            field=models.CharField(help_text='Unique PERSAL number', max_length=50, unique=True),
        ),
    ]
