# Generated by Django 4.2.11 on 2025-08-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='salary_level',
            field=models.CharField(blank=True, choices=[('LEVEL_1', 'Level 1 - General Assistant'), ('LEVEL_2', 'Level 2 - General Assistant'), ('LEVEL_3', 'Level 3 - General Assistant'), ('LEVEL_4', 'Level 4 - Administrative Officer'), ('LEVEL_5', 'Level 5 - Senior Administrative Officer'), ('LEVEL_6', 'Level 6 - Senior Administrative Officer'), ('LEVEL_7', 'Level 7 - Senior Administrative Officer'), ('LEVEL_8', 'Level 8 - Assistant Director'), ('LEVEL_9', 'Level 9 - Assistant Director'), ('LEVEL_10', 'Level 10 - Assistant Director'), ('LEVEL_11', 'Level 11 - Deputy Director'), ('LEVEL_12', 'Level 12 - Deputy Director'), ('LEVEL_13', 'Level 13 - Director'), ('LEVEL_14', 'Level 14 - Chief Director'), ('LEVEL_15', 'Level 15 - Deputy Director-General'), ('LEVEL_16', 'Level 16 - Director-General')], help_text='Public service salary level', max_length=20),
        ),
    ]
