# Generated by Django 4.2.11 on 2025-08-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_staff_salary_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='cell_number',
            field=models.CharField(blank=True, help_text='Mobile/cell phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='extension',
            field=models.CharField(blank=True, help_text='Office extension number', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, help_text='Office phone number', max_length=20),
        ),
    ]
