# Generated by Django 4.2.7 on 2025-08-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key for tracking user sessions', max_length=40, null=True),
        ),
    ]
