# Generated by Django 4.2.7 on 2025-08-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlog_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, PNG, max 2MB)', null=True, upload_to='profile_pictures/'),
        ),
    ]
