# Generated by Django 4.2.11 on 2025-08-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_staff_salary_level'),
        ('accounts', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='staff_member',
            field=models.OneToOneField(blank=True, help_text='Link to staff member record in organizational structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='core.staff'),
        ),
    ]
