# Generated by Django 4.2.7 on 2025-08-20 09:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reports.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        ('core', '0002_rename_targets_operationalplanitem_target_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.CharField(choices=[('EXCO_ONEPAGER', 'EXCO One-Pager'), ('KPA_DRILLDOWN', 'KPA Drill-down'), ('PROGRAMME_PACK', 'Programme Pack'), ('FINANCE_VIEW', 'Finance View'), ('SCM_TRACKER', 'SCM & Deliverables Tracker'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('output_format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel'), ('PPTX', 'PowerPoint'), ('JSON', 'JSON Data')], default='PDF', max_length=10)),
                ('filters', models.JSONField(default=dict, help_text='Report filters (KPAs, date ranges, units, etc.)')),
                ('parameters', models.JSONField(default=dict, help_text='Additional report parameters and settings')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='reports/generated/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Generated file size in bytes', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('is_scheduled', models.BooleanField(default=False, help_text='Whether this is a scheduled recurring report')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20)),
                ('next_run_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Request',
                'verbose_name_plural': 'Report Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=reports.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'csv'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(choices=[('EVIDENCE', 'Evidence Document'), ('TOR', 'Terms of Reference'), ('SCM', 'SCM Document'), ('REPORT', 'Report'), ('PHOTO', 'Photograph'), ('SPREADSHEET', 'Spreadsheet'), ('PRESENTATION', 'Presentation'), ('OTHER', 'Other Document')], default='OTHER', max_length=20)),
                ('title', models.CharField(help_text='Descriptive title for the attachment', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional description or notes')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this attachment can be viewed by all users')),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal Only'), ('RESTRICTED', 'Restricted Access'), ('CONFIDENTIAL', 'Confidential')], default='INTERNAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.operationalplanitem')),
                ('linked_progress_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='progress.progressupdate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
